version: '3.8'

services:
  postgres:
    image: postgres
    container_name: online-library-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST='localhost'
      - POSTGRES_DB='App'
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
    expose:
      - 5432

  django:
    container_name: online-library-django
    build: ./library
    expose:
      - 8001
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/backend/static

  nginx:
    container_name: online-library-nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/static
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: