version: '3.8'

services:
  postgres:
    image: postgres
    container_name: online-library-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST='localhost'
      - POSTGRES_DB='App'
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
    expose:
      - 5432

  django:
    container_name: online-library-django
    build: ./library
    ports:
      - 8001:8001
    depends_on:
      - postgres

volumes:
  postgres_data: